/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Platform_Types.h"

#define RCC_BASE_ADDRESS					0x40021000
#define GPIOA_BASE_ADDRESS					0x40010800

#define RCC_APB2ENR							(*(volatile uint32*)(RCC_BASE_ADDRESS + 0x18))
#define GPIOA_CRH							(*(volatile uint32*)(GPIOA_BASE_ADDRESS + 0x04))
#define GPIOA_ODR							(*(volatile uint32*)(GPIOA_BASE_ADDRESS + 0x0C))

#define RCC_APB2ENR_IOPAEN_BIT				2
#define GPIOA_CRH_MODE_PIN13_START_BIT		20
#define GPIOA_ODR_PIN13_BIT					13

#define SET_BIT(REG, BIT_NUM)				(REG |= (1 << BIT_NUM))
#define CLR_BIT(REG, BIT_NUM)				(REG &= ~(1 << BIT_NUM))
#define TOGGLE_BIT(REG, BIT_NUM)			(REG ^= (1 << BIT_NUM))


int main(void)
{
	//Enable Clock for Port A
    SET_BIT(RCC_APB2ENR, RCC_APB2ENR_IOPAEN_BIT);

    //Set Mode for Pin A13
    GPIOA_CRH &= ~(0b1111 << GPIOA_CRH_MODE_PIN13_START_BIT);
    GPIOA_CRH |= (2 << GPIOA_CRH_MODE_PIN13_START_BIT);

    uint32 index = 0;

	while(1)
	{
		TOGGLE_BIT(GPIOA_ODR, GPIOA_ODR_PIN13_BIT);
		for(index = 0; index < 10000; index++);
	}
}
